### ISSUE TITLE
Error when downloading languages

### ISSUE THREAD

**Issue by firstred** [PrestaShop/email-templates-sdk#1]
I get the following error when trying to download the languages with `gulp langs:dl`:

``` shell
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Hostname/IP doesn't match certificate's altnames: "Host: scritik.addons.prestashop.net. is not in the cert's altnames: DNS:*.prestashop.com, DNS:prestashop.com"
```

Does it need to be a different hostname?

**Comment by Scritik** [comment]
Hi @firstred,

I forgot to change the url, sorry about that. It should be fixed now :)

Emmanuel

**Comment by firstred** [comment]
That fixed it, thanks!

Going to check out this SDK. It looks promising!

**Comment by firstred** [comment]
Oh, wait. The response doesn't look too good:

``` json
{"errors":{"code":"0015","label":"Fatal error : method is undefined."}}
```

despite the HTTP 200 status code

**Comment by Scritik** [comment]
Oops. It's working on my dev environment but not on the production one. Let me check this.

**Comment by Scritik** [comment]
Now it's ok :)

Again, sorry.

**Comment by firstred** [comment]
Np, thanks for fixing it so quickly.
