### ISSUE TITLE
Custom variables do not work

### ISSUE THREAD

**Issue by wucherpfennig** [PrestaShop/email-templates-sdk#7]
I am not able to use custom variables:

```
# in footer.mjml
{{$var_name_lang}}
```

any suggestions?

**Comment by Scritik** [comment]
Hi,

Do you have your issue during the development or with the Emails manager module?

Make sure that you added your variable in both `settings.json` and `fake.json`

**Comment by wucherpfennig** [comment]
@Scritik 

thank you for your fast response. I found out that I need to do so and now it works :-)

you can close this issue
